name: Build Bisq 2

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  bitcoin-core-version: '23.0'
  electrumx-version: '1.16.0'
  elements-core-version: '0.21.0.2'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    name: Building on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Cache Bitcoin Core
        uses: actions/cache@v3
        with:
          path: tools/bitcoin-core
          key: ${{ runner.os }}-bitcoin-core-${{ env.bitcoin-core-version }}

      - name: Cache ElectrumX
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest' }}
        uses: actions/cache@v3
        with:
          path: tools/electrumx
          key: ${{ runner.os }}-electrumx-${{ env.electrumx-version }}

      - name: Cache Elements Core
        uses: actions/cache@v3
        with:
          path: tools/elements-core
          key: ${{ runner.os }}-elements-core-${{ env.elements-core-version }}

      - name: Install Wallets
        uses: ./.github/actions/install-wallets
        with:
          bitcoin-core-version: ${{ env.bitcoin-core-version }}
          electrumx-version: ${{ env.electrumx-version }}
          elements-core-version: ${{ env.elements-core-version }}

      - name: "Install Python"
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest' }}
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'tools/electrumx/electrumx-${{ env.electrumx-version }}/setup.py'

      - name: "Install leveldb (needed by ElectrumX)"
        if: ${{ matrix.os == 'macOS-latest' }}
        run: brew install leveldb gmp pkg-config

      - name: "Setup ElectrumX environment"
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest' }}
        run: pip install tools/electrumx/electrumx-${{ env.electrumx-version }}

      - name: Setup Java JDK
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache Electrum binaries
        uses: actions/cache@v3
        with:
          path: wallets/electrum/build/electrum_binaries
          key: ${{ runner.os }}-electrum-binaries-${{ hashFiles('wallets/electrum/build.gradle') }}

      - name: Gradle Build Action (root)
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build --scan

#      - name: Gradle Build Action (wallets)
#        uses: gradle/gradle-build-action@v2.3.3
#        with:
#          arguments: build --scan
#          build-root-directory: wallets
#          gradle-executable: ./gradlew
