name: Build Bisq 2

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    name: Building on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Gradle Build Action (root)
        uses: gradle/gradle-build-action@v2.7.1
        with:
          arguments: build --scan

      - name: Gradle Build Action (network)
        uses: gradle/gradle-build-action@v2.7.1
        with:
          arguments: build --scan
          build-root-directory: network
          gradle-executable: ./gradlew

      - name: Gradle Build Action (tor)
        uses: gradle/gradle-build-action@v2.7.1
        with:
          arguments: build --scan
          build-root-directory: network/tor
          gradle-executable: ./gradlew

      - name: Gradle Build Action (wallets)
        uses: gradle/gradle-build-action@v2.7.1
        with:
          arguments: build --scan
          build-root-directory: wallets
          gradle-executable: ./gradlew
