on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

      name:
        required: true
        type: string

      build-root-dir:
        required: true
        type: string

jobs:
  build:
    name: Build ${{ inputs.name }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '22'
          distribution: 'zulu'

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v3.5.0
        with:
          arguments: build -x test
          build-root-directory: ${{ inputs.build-root-dir }}
          gradle-executable: ./gradlew
          gradle-version: 8.9