name: Build Bisq 2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    name: Building on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Install Wallets
        uses: ./.github/actions/install-wallets
        with:
          bitcoin-core-version: '22.0'
          elements-core-version: '0.21.0.2'

      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Cache Electrum binaries
        uses: actions/cache@v3
        with:
          path: wallets/electrum/build/electrum_binaries
          key: ${{ runner.os }}-electrum-binaries-${{ hashFiles('wallets/electrum/build.gradle') }}

      - name: Gradle Build Action (root)
        uses: gradle/gradle-build-action@v2.2.2
        with:
          arguments: --stacktrace build

      - name: Gradle Build Action (wallets)
        uses: gradle/gradle-build-action@v2.2.2
        with:
          arguments: --stacktrace build
          build-root-directory: wallets
          gradle-executable: ./gradlew
