name: Build Bisq 2

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize, closed ]
    branches: [ main ]

permissions:
  contents: read

jobs:
  build_bisq:
    name: Build Bisq on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    uses: ./.github/workflows/build_bisq_module.yml
    with:
      os: ${{ matrix.os }}
      name: Bisq
      build-root-dir: .

  build_apps_module:
    name: Build apps module on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    uses: ./.github/workflows/build_bisq_module.yml
    with:
      os: ${{ matrix.os }}
      name: apps module
      build-root-dir: apps

  build_network_module:
    name: Build network module on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    uses: ./.github/workflows/build_bisq_module.yml
    with:
      os: ${{ matrix.os }}
      name: network module
      build-root-dir: network

  build_tor_module:
    name: Build tor module on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    uses: ./.github/workflows/build_bisq_module.yml
    with:
      os: ${{ matrix.os }}
      name: tor module
      build-root-dir: network/tor

  build_wallet_module:
    name: Build wallet module on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    uses: ./.github/workflows/build_bisq_module.yml
    with:
      os: ${{ matrix.os }}
      name: wallet module
      build-root-dir: wallets

  if_merged:
      if: github.event.pull_request.merged == true
      name: Push translation source files to Transifex
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
        - name: Push source files using transifex client
          uses: transifex/cli-action@v2
          with:
            token: ${{ secrets.TX_TOKEN }}
